-- MySQL Script generated by MySQL Workbench
-- Mon Jun 11 09:10:58 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ngpictures
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ngpictures` ;

-- -----------------------------------------------------
-- Schema ngpictures
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ngpictures` DEFAULT CHARACTER SET utf8 ;
USE `ngpictures` ;

-- -----------------------------------------------------
-- Table `ngpictures`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ngpictures`.`users` ;

CREATE TABLE IF NOT EXISTS `ngpictures`.`users` (
  `id` BIGINT(255) UNSIGNED NOT NULL AUTO_INCREMENT,
  `facebook_id` BIGINT(255) UNSIGNED NULL,
  `name` VARCHAR(60) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` TEXT NOT NULL,
  `bio` VARCHAR(255) NULL DEFAULT 'hey je suis sur Ngpictures 2.0',
  `phone` VARCHAR(45) NULL,
  `avatar` VARCHAR(500) NULL DEFAULT 'default.jpg',
  `confirmation_token` VARCHAR(75) NULL,
  `confirmed_at` DATETIME NULL,
  `reset_token` VARCHAR(75) NULL,
  `reset_at` DATETIME NULL,
  `remember_token` VARCHAR(75) NULL,
  `status` VARCHAR(45) NOT NULL DEFAULT 'users',
  `rank` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ngpictures`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ngpictures`.`categories` ;

CREATE TABLE IF NOT EXISTS `ngpictures`.`categories` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(300) NOT NULL,
  `date_created` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `title_UNIQUE` (`title` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ngpictures`.`posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ngpictures`.`posts` ;

CREATE TABLE IF NOT EXISTS `ngpictures`.`posts` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL,
  `content` LONGTEXT NULL,
  `exif` TEXT NULL,
  `date_created` DATETIME NOT NULL,
  `downloads` BIGINT(20) UNSIGNED NULL DEFAULT 0,
  `thumb` VARCHAR(500) NOT NULL,
  `slug` VARCHAR(300) NOT NULL,
  `online` TINYINT(4) UNSIGNED NULL,
  `users_id` BIGINT(255) UNSIGNED NOT NULL,
  `categories_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_articles_users_idx` (`users_id` ASC),
  INDEX `fk_posts_categories1_idx` (`categories_id` ASC),
  CONSTRAINT `fk_articles_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `ngpictures`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posts_categories1`
    FOREIGN KEY (`categories_id`)
    REFERENCES `ngpictures`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ngpictures`.`blog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ngpictures`.`blog` ;

CREATE TABLE IF NOT EXISTS `ngpictures`.`blog` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL,
  `content` LONGTEXT NULL,
  `exif` TEXT NULL DEFAULT NULL,
  `date_created` DATETIME NOT NULL,
  `downloads` BIGINT(20) UNSIGNED NULL DEFAULT 0,
  `thumb` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(300) NULL,
  `online` TINYINT(4) UNSIGNED NULL,
  `users_id` BIGINT(255) UNSIGNED NOT NULL,
  `categories_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_blog_users1_idx` (`users_id` ASC),
  INDEX `fk_blog_categories1_idx` (`categories_id` ASC),
  CONSTRAINT `fk_blog_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `ngpictures`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_blog_categories1`
    FOREIGN KEY (`categories_id`)
    REFERENCES `ngpictures`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ngpictures`.`albums`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ngpictures`.`albums` ;

CREATE TABLE IF NOT EXISTS `ngpictures`.`albums` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(500) NULL,
  `code` VARCHAR(20) NULL,
  `status` TINYINT(3) UNSIGNED NULL,
  `date_created` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ngpictures`.`gallery`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ngpictures`.`gallery` ;

CREATE TABLE IF NOT EXISTS `ngpictures`.`gallery` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `tags` TEXT NULL,
  `thumb` VARCHAR(500) NOT NULL,
  `description` TEXT NULL,
  `slug` VARCHAR(300) NULL,
  `downloads` BIGINT(20) UNSIGNED NULL DEFAULT 0,
  `exif` TEXT NULL DEFAULT NULL,
  `date_created` DATETIME NOT NULL,
  `online` TINYINT(4) UNSIGNED NOT NULL DEFAULT 0,
  `categories_id` INT UNSIGNED NOT NULL,
  `users_id` BIGINT(255) UNSIGNED NOT NULL,
  `albums_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_gallery_categories1_idx` (`categories_id` ASC),
  INDEX `fk_gallery_users1_idx` (`users_id` ASC),
  INDEX `fk_gallery_albums1_idx` (`albums_id` ASC),
  CONSTRAINT `fk_gallery_categories1`
    FOREIGN KEY (`categories_id`)
    REFERENCES `ngpictures`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gallery_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `ngpictures`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gallery_albums1`
    FOREIGN KEY (`albums_id`)
    REFERENCES `ngpictures`.`albums` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ngpictures`.`tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ngpictures`.`tags` ;

CREATE TABLE IF NOT EXISTS `ngpictures`.`tags` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ngpictures`.`gallery_tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ngpictures`.`gallery_tags` ;

CREATE TABLE IF NOT EXISTS `ngpictures`.`gallery_tags` (
  `gallery_id` INT UNSIGNED NOT NULL,
  `tags_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`gallery_id`, `tags_id`),
  INDEX `fk_gallery_has_tags_tags1_idx` (`tags_id` ASC),
  INDEX `fk_gallery_has_tags_gallery1_idx` (`gallery_id` ASC),
  CONSTRAINT `fk_gallery_has_tags_gallery1`
    FOREIGN KEY (`gallery_id`)
    REFERENCES `ngpictures`.`gallery` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gallery_has_tags_tags1`
    FOREIGN KEY (`tags_id`)
    REFERENCES `ngpictures`.`tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ngpictures`.`likes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ngpictures`.`likes` ;

CREATE TABLE IF NOT EXISTS `ngpictures`.`likes` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `date_created` DATETIME NOT NULL,
  `users_id` BIGINT(255) UNSIGNED NOT NULL,
  `posts_id` INT UNSIGNED NOT NULL,
  `gallery_id` INT UNSIGNED NOT NULL,
  `blog_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_likes_users1_idx` (`users_id` ASC),
  INDEX `fk_likes_posts1_idx` (`posts_id` ASC),
  INDEX `fk_likes_gallery1_idx` (`gallery_id` ASC),
  INDEX `fk_likes_blog1_idx` (`blog_id` ASC),
  CONSTRAINT `fk_likes_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `ngpictures`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_likes_posts1`
    FOREIGN KEY (`posts_id`)
    REFERENCES `ngpictures`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_likes_gallery1`
    FOREIGN KEY (`gallery_id`)
    REFERENCES `ngpictures`.`gallery` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_likes_blog1`
    FOREIGN KEY (`blog_id`)
    REFERENCES `ngpictures`.`blog` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ngpictures`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ngpictures`.`comments` ;

CREATE TABLE IF NOT EXISTS `ngpictures`.`comments` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `comment` MEDIUMTEXT NOT NULL,
  `date_created` DATETIME NOT NULL,
  `users_id` BIGINT(255) UNSIGNED NOT NULL,
  `posts_id` INT UNSIGNED NOT NULL,
  `gallery_id` INT UNSIGNED NOT NULL,
  `blog_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comments_users1_idx` (`users_id` ASC),
  INDEX `fk_comments_posts1_idx` (`posts_id` ASC),
  INDEX `fk_comments_gallery1_idx` (`gallery_id` ASC),
  INDEX `fk_comments_blog1_idx` (`blog_id` ASC),
  CONSTRAINT `fk_comments_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `ngpictures`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_posts1`
    FOREIGN KEY (`posts_id`)
    REFERENCES `ngpictures`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_gallery1`
    FOREIGN KEY (`gallery_id`)
    REFERENCES `ngpictures`.`gallery` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_blog1`
    FOREIGN KEY (`blog_id`)
    REFERENCES `ngpictures`.`blog` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ngpictures`.`verses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ngpictures`.`verses` ;

CREATE TABLE IF NOT EXISTS `ngpictures`.`verses` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(1000) NOT NULL,
  `ref` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ngpictures`.`online`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ngpictures`.`online` ;

CREATE TABLE IF NOT EXISTS `ngpictures`.`online` (
  `id` INT UNSIGNED NOT NULL,
  `online_time` TIMESTAMP NOT NULL,
  `date_created` DATETIME NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `users_id` BIGINT(255) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_online_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_online_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `ngpictures`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ngpictures`.`ideas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ngpictures`.`ideas` ;

CREATE TABLE IF NOT EXISTS `ngpictures`.`ideas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `content` LONGTEXT NOT NULL,
  `users_id` BIGINT(255) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ideas_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_ideas_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `ngpictures`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ngpictures`.`bugs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ngpictures`.`bugs` ;

CREATE TABLE IF NOT EXISTS `ngpictures`.`bugs` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `content` LONGTEXT NOT NULL,
  `users_id` BIGINT(255) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bugs_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_bugs_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `ngpictures`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ngpictures`.`following`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ngpictures`.`following` ;

CREATE TABLE IF NOT EXISTS `ngpictures`.`following` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `follower_id` BIGINT UNSIGNED NOT NULL,
  `followed_id` BIGINT UNSIGNED NOT NULL,
  `date_created` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_follewer_id_idx` (`follower_id` ASC),
  INDEX `fk_following_id_idx` (`followed_id` ASC),
  CONSTRAINT `fk_follower_id`
    FOREIGN KEY (`follower_id`)
    REFERENCES `ngpictures`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_followed_id`
    FOREIGN KEY (`followed_id`)
    REFERENCES `ngpictures`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
